repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
      - id: black
        language: python
        language_version: python310

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 --config tox.ini
        language: python
        language_version: python310
        additional_dependencies:
          - flake8-comprehensions ~= 3.10
        types: [ python ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-xml
      - id: check-yaml
        language: python
        exclude: condabuild/meta.yaml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        entry: mypy src/ test/
        args: [--config-file, pyproject.toml]
        files: \.pyi?$
        language: python
        language_version: python310
        pass_filenames: false
        additional_dependencies:
          - fluxus~=1.0
          - gamma-pytools~=3.0
          - openai
          - pandas-stubs
          - pytest
          - types-PyYAML
          - aiohttp
          - types-aiofiles

  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        # exclude all notebooks in the sphinx tutorials directory
        exclude: sphinx/source/.*\.ipynb$

  - repo: local
    hooks:
      - id: check-change-in-file-size
        name: 'Check change in file size'
        entry: hooks/check_change_in_file_size.sh
        language: system
        always_run: true
        pass_filenames: false
        stages: [ commit ]