name: artkit
channels:
  - bcgx
  - conda-forge
  - defaults
dependencies:
  # Python
  - python                   ~= 3.10.14

  # Additional libraries
  - fluxus                   ~= 1.0
  - gamma-pytools            ~= 3.0
  - pandas                   ~= 2.2
  - python-dotenv            ~= 1.0
  - graphviz                 ~= 9.0
  - python-graphviz          ~= 0.20

  # LLM provider packages:
  - openai                   ~= 1.34
  - groq                     ~= 0.9
  - anthropic                ~= 0.26
  - google-generativeai      ~= 0.6
  # The following are required for huggingface:
  - aiohttp                  ~= 3.9
  - pytorch                  ~= 2.3
  - transformers             ~= 4.41

  # Sphinx documentation build
  - nbsphinx                 ~= 0.9
  - sphinx                   ~= 7.2
  - sphinx-autodoc-typehints ~= 1.25
  - pydata-sphinx-theme      ~= 0.15.1
  - packaging                ~= 24.1

  # Notebooks
  - ipywidgets               ~= 8.1
  - jupyterlab               ~= 4.2
  - notebook                 ~= 7.2

  # DevOps
  - pytest                   ~= 8.2
  - pytest-asyncio           ~= 0.23
  - pytest-cov               ~= 5.0
  - pre-commit               ~= 3.7
